version: "3"
services:
  go-server:
    build:
        context: .
        dockerfile: Dockerfile.go-server
    ports:
      - '8153:8153'
      - '8154:8154'

  goagent_java:
    image: "gocd/gocd-agent"
    links:
      - go-server
    environment:
      AGENT_KEY: '123456789abcdef'
      AGENT_RESOURCES: 'java,python,test'
      GO_SERVER_URL: https://go-server:8154/go

  goagent_lua:
    build:
      context: .
      dockerfile: Dockerfile.lua-agent
    links:
      - go-server
    environment:
      AGENT_KEY: '123456789abcdef'
      AGENT_RESOURCES: 'gradle,java,lua'
      GO_SERVER_URL: https://go-server:8154/go

  provisioner:
    build:
      context: .
      dockerfile: Dockerfile.provisioner
    links:
      - go-server
