goserver:
  image: "gocd/gocd-server"
  hostname: go-server
  ports:
    - '8153:8153'
    - '8154:8154'

goagent_java:
  image: "gocd/gocd-agent"
  links:
    - goserver
  environment:
    AGENT_KEY: '123456789abcdef'
    AGENT_RESOURCES: 'java,test'

goagent_python3:
  image: "gocd/gocd-agent"
  links:
    - goserver
  environment:
    AGENT_KEY: '123456789abcdef'
    AGENT_RESOURCES: 'java,python3,test'
