# Previously Used  >> gocd/gocd-agent-alpine-3.6:v18.12.0 >> gocd/docker-gocd-agent-ubuntu-16.04

version: "2"
services:
  go-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '8153:8153'
      - '8154:8154'

  goagent_java:
    image: gocd/docker-gocd-agent-centos-7
    links:
      - go-server
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdef'
      AGENT_AUTO_REGISTER_RESOURCES: 'java,python,test'
      GO_SERVER_URL: https://go-server:8154/go

  goagent_lua:
    build:
      context: .
      dockerfile: Dockerfile.lua-agent
    links:
      - go-server
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdef'
      AGENT_AUTO_REGISTER_RESOURCES: 'gradle,java,lua'
      GO_SERVER_URL: https://go-server:8154/go
