go-server:
  image: gocd/gocd-server:v17.12.0
  ports:
    - '8153:8153'
    - '8154:8154'

goagent:
  image: gocd/gocd-agent-alpine-3.6:v17.12.0
  links:
    - go-server
  environment:
    GO_SERVER_URL: https://go-server:8154/go
    AGENT_AUTO_REGISTER_KEY: '123456789abcdef'
    AGENT_AUTO_REGISTER_RESOURCES: 'java,python,test'
